version: '3.7'

networks:
  cssninja-services:
    external: true

services:
  stylo-cooking:
    image: digisquad/cssninja.stylo.demo-cooking:latest
    restart: "unless-stopped"
    networks:
      - cssninja-services
    environment:
      - NUXT_PUBLIC_FRONTEND_URL=https://stylo-cooking.${HOST:-127.0.0.1.nip.io}/
    labels:
      traefik.enable: true
      traefik.docker.network: 'cssninja-services'
      traefik.http.routers.stylo-cooking-demo.entrypoints: 'http'
      traefik.http.routers.stylo-cooking-demo.rule: 'Host(`stylo-cooking.${HOST:-127.0.0.1.nip.io}`)'
      traefik.http.routers.stylo-cooking-demo.middlewares: 'https-redirect@file'
      traefik.http.services.stylo-cooking-demo-https.loadbalancer.server.port: 3000
      traefik.http.routers.stylo-cooking-demo-https.rule: 'Host(`stylo-cooking.${HOST:-127.0.0.1.nip.io}`)'
      traefik.http.routers.stylo-cooking-demo-https.tls: true
      traefik.http.routers.stylo-cooking-demo-https.entrypoints: 'https'
      traefik.http.routers.stylo-cooking-demo-https.tls.certresolver: 'http'
